# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SMGene.py

on: push

jobs:     
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
    - name: Test with integrated tester
      run: |
        python SMGeneTest.py -u unittest_example.yml
    - name: Archive result
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: test_report.txt
